const bookingForm=document.querySelector('#bookingForm'),paymentModal=document.querySelector('#paymentModal'),ticketModal=document.querySelector('#ticketModal'),paymentForm=document.querySelector('#paymentForm');let pendingBooking=null,currentMethod='upi',lastTicket=null;
function money(value){return `₹${Number(value).toLocaleString('en-IN')}`}
function modal(el,open){el.classList.toggle('open',open);el.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''}
bookingForm.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();if(!bookingForm.checkValidity()){bookingForm.reportValidity();return}const option=eventSelect.selectedOptions[0];pendingBooking={name:document.querySelector('#name').value.trim(),email:document.querySelector('#email').value.trim(),event:eventSelect.value,tickets:Number(tickets.value),total:Number(option.dataset.price)*Number(tickets.value)};document.querySelector('#payEvent').textContent=`${pendingBooking.event} · ${pendingBooking.tickets} ticket${pendingBooking.tickets>1?'s':''}`;document.querySelector('#payAmount').textContent=money(pendingBooking.total);document.querySelector('#buttonAmount').textContent=money(pendingBooking.total);modal(paymentModal,true)},true);
document.querySelectorAll('[data-close-payment]').forEach(x=>x.addEventListener('click',()=>modal(paymentModal,false)));document.querySelectorAll('[data-close-ticket]').forEach(x=>x.addEventListener('click',()=>modal(ticketModal,false)));
document.querySelectorAll('[data-method]').forEach(btn=>btn.addEventListener('click',()=>{currentMethod=btn.dataset.method;document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===currentMethod))}));
const card=document.querySelector('#cardNumber'),expiry=document.querySelector('#expiry');card.addEventListener('input',()=>card.value=card.value.replace(/\D/g,'').slice(0,16).replace(/(.{4})/g,'$1 ').trim());expiry.addEventListener('input',()=>{let v=expiry.value.replace(/\D/g,'').slice(0,4);expiry.value=v.length>2?`${v.slice(0,2)}/${v.slice(2)}`:v});
function validPayment(){if(currentMethod==='upi')return /^[\w.-]{2,}@[\w.-]{2,}$/.test(document.querySelector('#upiId').value.trim());if(currentMethod==='card')return card.value.replace(/\s/g,'').length===16&&/^\d{2}\/\d{2}$/.test(expiry.value)&&/^\d{3}$/.test(document.querySelector('#cvv').value);return Boolean(document.querySelector('#bank').value)}
paymentForm.addEventListener('submit',e=>{e.preventDefault();if(!validPayment()){notify(`Please enter valid ${currentMethod==='bank'?'bank details':currentMethod.toUpperCase()+' details'}`);return}const button=paymentForm.querySelector('.pay-button');button.disabled=true;button.querySelector('span').textContent='Processing…';setTimeout(()=>{const id=`EX${Date.now().toString().slice(-8)}`;lastTicket={...pendingBooking,id,method:currentMethod,bookedAt:new Date().toLocaleString('en-IN')};const saved=JSON.parse(localStorage.getItem('eventxBookings')||'[]');saved.push(lastTicket);localStorage.setItem('eventxBookings',JSON.stringify(saved));document.querySelector('#ticketEvent').textContent=lastTicket.event;document.querySelector('#ticketGuest').textContent=lastTicket.name;document.querySelector('#ticketCount').textContent=lastTicket.tickets;document.querySelector('#ticketId').textContent=id;document.querySelector('#ticketPaid').textContent=money(lastTicket.total);modal(paymentModal,false);modal(ticketModal,true);bookingForm.reset();paymentForm.reset();updateTotal();button.disabled=false;button.querySelector('span').textContent='Pay securely'},1400)});
document.querySelector('#downloadTicket').addEventListener('click',()=>{if(!lastTicket)return;const receipt=`EVENTX DIGITAL TICKET\n=====================\nBooking ID: ${lastTicket.id}\nEvent: ${lastTicket.event}\nGuest: ${lastTicket.name}\nEmail: ${lastTicket.email}\nTickets: ${lastTicket.tickets}\nAmount Paid: ${money(lastTicket.total)}\nPayment: ${lastTicket.method.toUpperCase()} (DEMO)\nBooked: ${lastTicket.bookedAt}\n\nThank you for choosing EventX.`;const blob=new Blob([receipt],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`EventX-${lastTicket.id}.txt`;a.click();URL.revokeObjectURL(url);notify('Ticket downloaded')});
addEventListener('keydown',e=>{if(e.key==='Escape'){modal(paymentModal,false);modal(ticketModal,false)}});
