const header=document.querySelector('.site-header');const menu=document.querySelector('.menu-btn');const nav=document.querySelector('.nav');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>35));
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.querySelectorAll('.nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.event-card').forEach(card=>card.classList.toggle('hidden',btn.dataset.filter!=='all'&&card.dataset.category!==btn.dataset.filter))}));
const toast=document.querySelector('#toast');function notify(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
document.querySelectorAll('.event-image button').forEach(btn=>btn.addEventListener('click',()=>{btn.classList.toggle('saved');btn.textContent=btn.classList.contains('saved')?'♥':'♡';notify(btn.classList.contains('saved')?'Saved to your favourites':'Removed from favourites')}));
const eventSelect=document.querySelector('#event');const tickets=document.querySelector('#tickets');const total=document.querySelector('#total');function updateTotal(){const option=eventSelect.selectedOptions[0];const price=Number(option?.dataset.price||0);total.textContent=`₹${(price*Number(tickets.value)).toLocaleString('en-IN')}`};eventSelect.addEventListener('change',updateTotal);tickets.addEventListener('change',updateTotal);
document.querySelectorAll('.card-book').forEach(btn=>btn.addEventListener('click',()=>{eventSelect.value=btn.dataset.event;updateTotal();document.querySelector('#booking').scrollIntoView({behavior:'smooth'})}));
document.querySelector('[data-video]').addEventListener('click',()=>notify('EventX story video — coming soon!'));
document.querySelector('#bookingForm').addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#name');const email=document.querySelector('#email');const message=document.querySelector('#formMessage');if(!e.currentTarget.checkValidity()){e.currentTarget.reportValidity();return}const option=eventSelect.selectedOptions[0];const booking={name:name.value.trim(),email:email.value.trim(),event:eventSelect.value,tickets:Number(tickets.value),total:Number(option.dataset.price)*Number(tickets.value),bookedAt:new Date().toISOString()};const bookings=JSON.parse(localStorage.getItem('eventxBookings')||'[]');bookings.push(booking);localStorage.setItem('eventxBookings',JSON.stringify(bookings));message.textContent=`✓ Booking confirmed for ${booking.event}!`;notify('Your EventX booking is confirmed 🎉');e.currentTarget.reset();updateTotal();setTimeout(()=>message.textContent='',5000)});
